README.md

add project details to readme

---

index.html

create HTML and folder structure

---

index.html
scripts/api.js

add js scripts for XMLhttpRequest

---

index.html
scripts/api.js

by using foreach loop, we append titles and images
relates #9

add titles and images

---

index.html
scripts/api.js

complete new stories for different countries

---

scripts/api.js

add links to each storyblock

---

.gitignore
package.json
scripts/api.js
scripts/test.js

add test.js files

---

scripts/api.js

add summary to story

---

scripts/api.js

improve accessibility by adding alt text

---

index.html
style/style.css

add style.css for mobiles but still need more work to be done for devices with wider browser

add Mobile-first css file 

---

package-lock.json
package.json
scripts/global.js
scripts/updateContent.js
tests/test.js

add tests for flag url function

---

scripts/api.js
scripts/createTemplate.js
style/style.css

added css for header for desktop and also manage to align text content to the left.
relates #35 #36

fix css for header and align text to the left

---

scripts/api.js

fix console.logs

---

scripts/api.js

Revert "fix console.logs"

---

style/style.css

remove comment in css

---

index.html

add closing head tag

---

index.html

Issuefixer

---

scripts/api.js
scripts/createTemplate.js

change naming for create/appending function for flag and news

---

README.md

add chrome extension link to readme

---

index.html
scripts/api.js
scripts/createTemplate.js

Add a link to see more news 

---

scripts/api.js
scripts/createTemplate.js
scripts/global.js

rename URL and add clarity comments
